title: "Individual Project Portfolio 2"
description: "Industrial XR Project â€“ Individual Contribution Portfolio"
author: "Laheeq Syed"

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed

header_pages:
  - index.md
  - contributions.md
  - Reflection.md
  - peer-feedback.md
  - ethics.md
